language: c

sudo: required

before_install: 
 - sudo apt-get update -qq
 - sudo apt-get install -qq subversion bison gawk make gcc g++ xz-utils libxml2-utils xsltproc docbook2x libncurses5-dev texinfo git uuid-dev autoconf unionfs-fuse squashfs-tools genisoimage dosfstools
 - sudo useradd lfs -m -s /bin/bash
 - sudo usermod -aG sudo lfs

script:
 - mkdir -p ./GoboLinux
 - ./GoboALFS --batch ./GoboLinux

